# SITE CONFIGURATION
baseurl: ""
url: "http://www.laskaridis.com"

permalink: /insights/:year/:month/:day/:title

markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
